# Generated by Django 4.2.8 on 2023-12-11 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 2, 15, 1, 453949), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='short_description',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 2, 15, 1, 454950), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 12, 2, 15, 1, 455952), verbose_name='Дата заказа'),
        ),
    ]
