# Generated by Django 4.2.8 on 2023-12-15 19:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_blog_posted_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 15, 22, 53, 2, 332879), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 15, 22, 53, 2, 348501), verbose_name='Дата заказа'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date', models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 15, 22, 53, 2, 332879), verbose_name='Дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.catalog', verbose_name='Товар комментария')),
            ],
            options={
                'verbose_name': 'Комментарии к товару',
                'verbose_name_plural': 'Комментраии к товарам',
                'db_table': 'Comment',
                'ordering': ['-date'],
            },
        ),
    ]
